In [1]:
Distance=[15,20,21,24]
Time=[6,4,3,2]

In [3]:
speed=Distance/Time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
t1=(15,20,21,24)
t2=(6,4,3,2)

In [7]:
result_add=t1+t2
result_add

(15, 20, 21, 24, 6, 4, 3, 2)

In [9]:
import numpy as np

In [11]:
dist_array=np.array(t1)
time_array=np.array(t2)

In [13]:
type(dist_array)

numpy.ndarray

In [15]:
type(time_array)

numpy.ndarray

In [19]:
speed = dist_array/time_array
speed

array([ 2.5,  5. ,  7. , 12. ])

In [21]:
##basic attributes of an array###
array1=np.array([15,20,21,24])

In [23]:
array1.ndim

1

In [25]:
array1.size

4

In [27]:
##create a 2D array
array2=np.array([[10,11,12,14,15],[20,21,13,23,26]])
print(array2)
print(array2.ndim)
print(array2.size)
print(array2.shape)

[[10 11 12 14 15]
 [20 21 13 23 26]]
2
10
(2, 5)


In [37]:
### Create a 3D array:
array3=np.array([[[5,6,7,8],[10,11,12,13]],[[14,15,16,17],[18,19,20,21]]])
print(array3)
print(array3.ndim)
print(array3.size)
print(array3.shape)

[[[ 5  6  7  8]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]]
3
16
(2, 2, 4)


In [39]:
### Create a 3D array:
array3=np.array([[[5,6,7,8],[10,11,12,13]],[[14,15,16,17],[18,19,20,21]],[[20,21,22,23],[24,25,26,27]]])
print(array3)
print(array3.ndim)
print(array3.size)
print(array3.shape)

[[[ 5  6  7  8]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]

 [[20 21 22 23]
  [24 25 26 27]]]
3
24
(3, 2, 4)


In [79]:
### Create a 1d array with elements 1-12
array1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array1d)
print(f"the dimension of array is: {array1d.ndim}")
print(f"the size of array is: {array1d.size}")
print(f"the shape of array is: {array1d.shape}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
the dimension of array is: 1
the size of array is: 12
the shape of array is: (12,)


In [73]:
#### Create a 2D array with the same elements 1-12
array2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2d)
print(f"the dimension of array is: {array2d.ndim}")
print(f"the size of array is: {array2d.size}")
print(f"the shape of array is: {array2d.shape}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the dimension of array is: 2
the size of array is: 12
the shape of array is: (3, 4)


In [75]:
#### create a 3D array with the same elements 1-12
array3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array3d)
print(f"the dimension of array is: {array3d.ndim}")
print(f"the size of array is: {array3d.size}")
print(f"the shape of array is: {array3d.shape}")

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
the dimension of array is: 3
the size of array is: 12
the shape of array is: (3, 2, 2)


#### Convert an array from a lower dimesion to higher dimension

In [81]:
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
### to change the shape of an array we use the reshape method
array_2d = array1d.reshape(4,3)
print(array_2d)
print(f"the dimension of array is: {array_2d.ndim}")
print(f"the size of array is: {array_2d.size}")
print(f"the shape of array is: {array_2d.shape}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
the dimension of array is: 2
the size of array is: 12
the shape of array is: (4, 3)


In [85]:
array_3d = array1d.reshape(2,3,2)
print(array_3d)
print(f"the dimension of array is: {array_3d.ndim}")
print(f"the size of array is: {array_3d.size}")
print(f"the shape of array is: {array_3d.shape}")

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
the dimension of array is: 3
the size of array is: 12
the shape of array is: (2, 3, 2)


#### Converting higher dimensional array to lower dimension - flatten() or ravel()

In [89]:
converted_id = array_3d.flatten()
converted_id

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [91]:
reduced_1d = array_2d.ravel()
reduced_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Slicing of Array

In [97]:
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
### slice out the elements 2-7 from the above array:
array1d[1:7]

array([2, 3, 4, 5, 6, 7])

In [101]:
array1d[-11:-5]

array([2, 3, 4, 5, 6, 7])

In [103]:
#### syntax for slicing = [start:stop:step]

In [105]:
#### read all elements starting from 4
array1d[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
#### slice a 2D array:
array2

array([[10, 11, 12, 14, 15],
       [20, 21, 13, 23, 26]])

In [109]:
# slice out elements 23 and 13 from the above array

In [119]:
array2[1,2:4]

array([13, 23])

In [122]:
first_cyclist = [10,15,17,26] #distance covered by the 1st cyclist in 4 trials
second_cyclist = [12,11,21,24] #distance covered by the 2nd cyclist in 4 trials

In [124]:
first_cyclist_array = np.array(first_cyclist)
second_cyclist_array = np.array(second_cyclist)

In [130]:
cyclists = np.array([[10,15,17,26],[12,11,21,24]])
cyclists

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [160]:
### find the total distance covered by both the cyclists in 4 trials
total_distance = first_cyclist_array + second_cyclist_array
total_distance

array([22, 26, 38, 50])

In [162]:
#### find the total distance covered by both of them in the first 
cyclists[:,0]

array([10, 12])

In [164]:
#### find the distance covered by the fisrt cyclist in all 4 trials
cyclists[0,:]

array([10, 15, 17, 26])

In [166]:
#### find the distance covered by the fisrt cyclist in first trials
first_cyclist_array[0]

10

In [168]:
cyclists[0,0]

10