In [1]:
def sum_of(x,y):
    add=x+y
    return add

In [2]:
sum_of(10,8)

18

In [3]:
def sum_of1(x,y):
    add=x+y
    print(add)

In [4]:
sum_of1(37,9)

46


In [5]:
def welcome(name):
    return f"Hi,{name}!"


In [7]:
welcome('Akansha')

'Hi,Akansha!'

In [8]:
def welcome(name):
    return "Hi,{name}!"


In [9]:
welcome('Kim')

'Hi,{name}!'

##### Built in Functions:

In [10]:
my_list=[7,8,2,0,45,78]
len(my_list)

6

In [11]:
type(my_list)

list

###### Lambda Functions-:

In [1]:
#### Anonymous functions,used for simple operations,requires no indentation,created in a single line

In [16]:
result= lambda x,y,b:(x+y)-b

In [17]:
result(5,7,2)

10

In [20]:
def lambda_equal(x,y,b,z):
    result=(x+y)-b
    return result

In [21]:
lambda_equal(10,6,3)

TypeError: lambda_equal() missing 1 required positional argument: 'z'

In [22]:
def lambda_equal1(x,y,b,z):
    z=(x+y)-b
    return z

In [25]:
lambda_equal1(4,5,2,10)

7

In [26]:
 def lambda_swapnil(x,y,b,z):
    z=(x+y)-(b+z)
    return z
    
    

In [27]:
lambda_swapnil(3,4,5,6)

-4

In [28]:
tim=78
tim=65
tim

65

##### Recursive functions-: the functions that call themselves within the definition. Helps to break up a big job into smaller similar tasks

In [29]:
def factorial(mad):
    if mad==1:
        return 1
    else:
        return mad*factorial(mad-1)
    

In [30]:
factorial(6)

720

###### Generator Functions-:  this function yeild values one at a time and generates a sequence of values using the yeild keyword.

In [43]:
def my_gen():
    for x in range(2,10):
        yield x
        

In [44]:
for number in my_gen():
    print(number)

2
3
4
5
6
7
8
9


In [45]:
###the output of the my_gen function is stored in an object.---to get the values the object stores i have to use a for loop
### to print each value stored OR we use the next statement

In [47]:
X=my_gen()
print(next(X))
print(next(X))
print(next(X))
print(next(X))
print(next(X))
print(next(X))
print(next(X))
print(next(X))


2
3
4
5
6
7
8
9


#### Differences-:

*  Yeild statement in a generator saves the state of a function. With the 'Next' statement the function is called again and the excecution happens from the next value(not the initial value,execution happens with the recent value).The return statement terminates the function completely.

* The generators do not run the function it creates a state of the function and gives us a generator object,to get the value the object stores we have to use the next statement for a 'for in' loop

In [48]:
#Q)create a list with values from 20-31 using the range function and print the list

In [ ]:
list_range=list(range(20,31))
print(list_range)

In [49]:
#Q)Find out the maximum value in a given collection (56,78,23,45,82,13)

In [55]:
numbers=[56,78,23,45,82,13]
max_num= max(numbers)
max_num

82

In [56]:
min_num=min(numbers)
min_num

13

In [50]:
#Q) create a custom function with 3 objects m,n,p  where a=m+n,b=n+p,c=m+p--> test it for different values for m,n,p

In [57]:
def fun1(m,n,p):
    a=m+n
    b=n+p
    c=p+m
    print(a,b,c)

In [58]:
fun1(6,5,10)

11 15 16


In [68]:
fun1(p=5,n=6,m=10)

16 11 15


In [51]:
#Q) create a generator function which will give us the odd numbers from the natural number list.

In [59]:
def odd_numbers():
    n=1
    n=n+2
    yield n
    n=n+2
    yield n
    n=n+2
    yield n

In [60]:
odd=odd_numbers()
print(next(odd))
print(next(odd))
print(next(odd))

3
5
7


In [84]:
def odd_gen(lim):
    for x in range (1,lim+1):
        if(x%2==1):
            yield x
for x in odd_gen(20):
    print(x)

1
3
5
7
9
11
13
15
17
19


##### Function with Keyword Arguments:

In [62]:
def kwfunc(name,score):
    print(f"Name:{name},Score:{score}")

In [67]:
kwfunc('John',80)

Name:John,Score:80


In [66]:
kwfunc(95,'Sim')  

Name:95,Score:Sim


In [65]:
kwfunc(score=95,name='Sim')

Name:Sim,Score:95


###### Function with positional arguments:

In [69]:
### say we do not have an idea on the number of parameters we pass to the function-:
def fun3(*my_values):
    for i in my_values:
        print(i)

In [72]:
fun3('This','is','a','mutable','parameter')

This
is
a
mutable
parameter


In [73]:
fun3('This','is','a','mutable','parameter','list')

This
is
a
mutable
parameter
list


In [74]:
# *args---> helps us to pass a varying list of parameters to a function.

In [75]:
###* kwargs---> works with varying number of keywords

In [76]:
def fun4(**kid):
    print("The kid name is "+kid['grade'])

In [78]:
fun4(name='peppa',surname='pig',grade='nursery',cartoon='Masha',gender='Male')

The kid name is nursery


In [79]:
def fun4(**kid):
    print("The kid name is "+kid['name'])

In [80]:
fun4(name='peppa',surname='pig',grade='nursery',cartoon='Masha',gender='Male')

The kid name is peppa


In [81]:
def fun4(**what):
    print("The kid name is "+what['name'])

In [82]:
fun4(name='peppa',surname='pig',grade='nursery',cartoon='Masha',gender='Male')

The kid name is peppa


In [2]:
Distance=[15,20,21,24]
Time=[6,4,3,2]

In [3]:
speed=Distance/Time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
t1=(15,20,21,24)
t2=(6,4,3,2)

In [5]:
result_add=t1+t2
result_add

(15, 20, 21, 24, 6, 4, 3, 2)

In [6]:
import numpy as np

In [8]:
dist_array=np.array((15,20,21,24))

In [9]:
time_array=np.array(t2)

In [10]:
type(dist_array)

numpy.ndarray

In [11]:
type(time_array)

numpy.ndarray

In [12]:
speed=dist_array/time_array

In [13]:
speed

array([ 2.5,  5. ,  7. , 12. ])

In [14]:
##basic attributes of an array###
array1=np.array([15,20,21,24])

In [15]:
array1.ndim

1

In [16]:
array1.size

4

In [17]:
##create a 2D array
array2=np.array([[10,11,12,14,15],[20,21,13,23,26]])
print(array2)
print(array2.ndim)
print(array2.size)
print(array2.shape)

[[10 11 12 14 15]
 [20 21 13 23 26]]
2
10
(2, 5)


In [18]:
### Create a 3D array:
array3=np.array([[[5,6,7,8],[10,11,12,13]],[[14,15,16,17],[18,19,20,21]],[[20,21,22,23],[24,25,26,27]]])
print(array3)
print(array3.ndim)
print(array3.size)
print(array3.shape)

[[[ 5  6  7  8]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]

 [[20 21 22 23]
  [24 25 26 27]]]
3
24
(3, 2, 4)


In [ ]:
### Create a 1d array with elements 1-12
#### Create a 2D array with the same elements 1-12
#### create a 3D array with the same elements 1-12